### ISSUE TITLE
Shows a duplicated favicon (only on the first page)

### ISSUE THREAD

**Issue by tuurep** [DrHaid/startpage-result-favicons#1]
## Bug description

Icon is duplicated *on the first page only*. When you navigate to any other page, it looks like it's working as intended. Returning to the first page, icon still duplicated.

In the Mozilla Addons page's reviews, I see a similar experience in a review by VanRook:

> It fulfills its function very well, the only problem is that the icons are duplicated or even quintuplicated, fix this if you can please! I can share screenshot if you want

I can't reproduce a case for quintuplicated icons.

## My screenshots

![image](https://github.com/user-attachments/assets/ab20fbfd-c3b0-44e7-8b12-22371040dc01)

![image](https://github.com/user-attachments/assets/57173e94-9aa3-41f3-b1c2-36174160b0ca)

**Comment by DrHaid** [comment]
Interesting 🤔 I've never encountered any duplication while testing or using the add-on myself.
What I've seen though is that sometimes initially no favicons show up at all. Might be a related issue.

Could you give me some info about your system?
- Operating system
- Firefox version
- Other extensions you might be using that could mess with the DOM (Popup/Ad blockers)

Maybe that'll give me a hint on how to reproduce this.

**Comment by tuurep** [comment]
Hey first and foremost I've found out that when I toggle off "Appearance > Instant Answers" in the settings, the favicon is no longer duplicated. This seems consistent: 
* "Instant Answers" on: icon duplicates
* "Instant Answers" off: no duplication

May or may not be related: for me the "Instant Answers" widgets (or whatever they're called) load pretty slowly. But the duplicated icon is there even before they load so hmm.

Do you toggle this setting off yourself?

In case something more is related, here's system info:

* Arch Linux
* ```
  $ firefox --version
  Mozilla Firefox 131.0.2
  ```
* I possibly have many.. maybe most notable are *uBlock Origin* and *I still don't care about cookies*

I'll try with a clean firefox profile next (to rule out extensions interference)

**Comment by tuurep** [comment]
Clean profile test:

Yes same thing happens when this addon is the only one added to firefox

So icon duplicates when "Instant Answers" on (default), otherwise not. Hopefully this is a good clue.

**Comment by DrHaid** [comment]
Hmmm okay. Thank you for all your testing!
My system looks pretty similar (Arch Linux, Firefox Version, add-ons etc.) and my "Instant Answers" are also enabled 🤔
Toggling it on and off also didn't change anything for me.

I'll take a closer look at the code as soon as I can. Maybe I can spot something wrong.

**Comment by tuurep** [comment]
Strange, in that case I would have really expected you to have the same issue..

So I know the Instant Answers -widgets come from something called SearchExpander ([searchexpander.com](https://www.searchexpander.com/)), and devtools console can show errors like this:

![image](https://github.com/user-attachments/assets/b3595b25-cc79-4e07-aebe-ca1d0ce073a4)

Could very well be unrelated but it's an idea. :D

**update:** I've now got some cases where Instant Answers is on, and icon is *not* duplicated. Can't quite say what the difference was, but the console did have the same warnings as above. At first I thought it was when I tried changing 'favicon source' from DuckDuckGo to Google as I found that setting, but it's not consistent: it still duplicates the icon most of the time.

**Comment by DrHaid** [comment]
Whoops, the PR closed the issue automatically. I added a check now to make sure icons aren't added if they already exist.

It could have to do with the Instant Answers. FYI: Some time ago Startpage changed something so the search results would be added after the initial loading of the page, so I had to make sure the results have been loaded before adding any icons. This works by observing the results container for changes and then adding the favicons. Maybe the slow loading of the widget triggers the observer a second time? I couldn't reliably reproduce it, though.

Anyway this solution should prevent it from happening again, no matter what was causing it.

**Comment by tuurep** [comment]
Yeah looks like the duplicated icon is fixed, thank you!

I've still had some issue with sometimes no favicon loading, perhaps similar to:

> What I've seen though is that sometimes initially no favicons show up at all. Might be a related issue.

Didn't want to overwhelm with adjacent-yet-maybe-not-related issue earlier so I didn't mention it but sadly your fix doesn't address that case.

What I mean is that sometimes the icon never loads, not only a long load time. Having trouble getting it to happen right now but I'll keep an eye on it.

The way it seemed like to me was:
* Instant Answers on: Icon loads 1-2 times (1 is rare)
* Instant Answers off: Icon loads 0-1 times (0 is rare)

**Edit:**

I see now that there was a commit related to this in #4, and verified my addon is still 0.1.5,

Let's see if this problem is resolved when I update to 0.1.6

**Comment by tuurep** [comment]
Hey I have some bad news

On 0.1.6, I don't get any favicons at all, 100% of the time :smile:

So I suppose 882fa4271f29 causes this somehow, as that's the only change since

**Comment by kinoegit** [comment]
Yes since ca 30 minutes ago favicons disappeared. Before I had duplicated icons for ca 2 months

**Comment by DrHaid** [comment]
Man, I really thought I had it 🙈 This is really hard to debug, it's all working for me.
Heigh-ho, back to work I go 🏃

**Comment by tuurep** [comment]
Yeah it's pretty unfortunate, I'll keep testing on my end and can let you know here :smile:

**Comment by tuurep** [comment]
0.1.7 at least with some quick testing works!

@kinoegit how does it look for you? (may require manually updating)

**Comment by kinoegit** [comment]
Its fixed again here by version 0.1.7. Thanks a lot DrHaid!

**Comment by tuurep** [comment]
Nice, thanks :)

By the way, I've seen some Reddit comments from Startpage's accounts that first-party favicons may be a thing in the future: [example comment](https://www.reddit.com/r/StartpageSearch/comments/1cur5yo/comment/l4whbpz/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

But it's been a long time and for the foreseeable future looks like we still need this addon

To me it's so essential.. Can distinguish websites at a glance without having to *read* all the URLs :smile:

**Comment by DrHaid** [comment]
Yeah it's really convenient. Good to know they're working on a proper feature. Possibly even less error prone than this 😅
