### ISSUE TITLE
Chrome version so can be used with Brave browser <4

### ISSUE THREAD

**Issue by alexvaltchev** [DrHaid/startpage-result-favicons#7]
I love this extension for my Firefox and works brilliant. Thank you!
IS it possible to make this extension available for Chrome too, so I can use it with Brave browser?
I tried Foxify to make it work with it but does not work. Please make Chrome version I would love to use it! Thank you a lot!!!

**Comment by DrHaid** [comment]
I'm on it 👍

**Comment by alexvaltchev** [comment]
Thank you so much ❤️ You are awesome 😊 I wish that search engine showed icons by default but your extension does fix exactly that!

Kind regards,
Alex

Kind regards,
Alex
________________________________

**Comment by alexvaltchev** [comment]
@DrHaid  how do I put this into my Brave browser? I don't see it in the Chrome store. Please help me understand how to install it. Thank you :)

**Comment by alexvaltchev** [comment]
I found the ZIP file and extected it but there was error in the manifest.json

I had to add "version" line as the AI suggested. Then I was able to install it as unpacked extention. However still does not work.

![Screenshot_3](https://github.com/user-attachments/assets/f711b631-a7be-4dd8-a245-97f2dae97720)
![Screenshot_4](https://github.com/user-attachments/assets/101478ac-93db-4f62-85f2-b2737198bfee)

It cannot find favorite icon site. Also I clicked the "Hide anonymous view" but it goes back to OFF.

**Comment by alexvaltchev** [comment]
Can you please fix it and add it to Chrome extension
 store? I am waiting to use it :) Thank you so much!

**Comment by DrHaid** [comment]
Yeah sorry, it wasn't in the store yet because it was still being reviewed by Google.
You can get it in the Chrome web store now:
[https://chromewebstore.google.com/detail/startpage-result-favicons/nhkmmadlllffbakghicnimbohdcnohcl](https://chromewebstore.google.com/detail/startpage-result-favicons/nhkmmadlllffbakghicnimbohdcnohcl)

Let me know if there are any issues.

**Comment by alexvaltchev** [comment]
Thank you. Yep I got it just now it works perfect! Thank you so much!
